// `node scripts/ai-score-shares.ts`: write packages/chaff/src/ai-score/human-shares.ts, the human shares the AI-likeness
// quick score compares with, from the committed corpus/rules-measure.json. `yarn rules:measure --write` (and --apply)
// runs it after writing the measurement, so the two move together; test/test_ai_score_shares.ts holds them equal.
//   --check   print nothing and fail when the module is not what the measurement gives
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { format, resolveConfig } from "prettier";
import { allRules, readMeasurement } from "./rules-measure-files.ts";
import type { Measurement } from "./rules-measure-score.ts";
import { scoredSignalIds } from "../packages/chaff/src/ai-score/signals.ts";
import type { HumanShares } from "../packages/chaff/src/ai-score/score.ts";
import type { RuleDefinition } from "../packages/chaff/src/plugin.ts";

export const SHARES_MODULE = join(import.meta.dirname, "..", "packages", "chaff", "src", "ai-score", "human-shares.ts");

/** The measurement's groups for the rules the score counts, in rule order. A rule the measurement lacks has no groups. */
export const aiScoreSharesOf = (measurement: Measurement, rules: readonly RuleDefinition[]): HumanShares =>
  Object.fromEntries(scoredSignalIds(rules).map((id) => [id, measurement.rules[id]?.groups ?? {}]));

const HEADER = [
  "// Generated by scripts/ai-score-shares.ts from corpus/rules-measure.json: `yarn rules:measure --write` rewrites it. Do not edit.",
  'import type { HumanShares } from "./score.ts";',
  "",
  "/** On how many human documents of each genre group each AI-shape rule reported, at the genre's level. */",
];

const moduleText = async (shares: HumanShares): Promise<string> => {
  const text = [...HEADER, `export const HUMAN_SHARES: HumanShares = ${JSON.stringify(shares)};`, ""].join("\n");
  return format(text, { ...(await resolveConfig(SHARES_MODULE)), filepath: SHARES_MODULE });
};

/** Writes the module from a measurement, as `yarn rules:measure --write` leaves it. */
export const writeAiScoreShares = async (measurement: Measurement): Promise<void> => {
  writeFileSync(SHARES_MODULE, await moduleText(aiScoreSharesOf(measurement, allRules())));
};

if (import.meta.main) {
  const expected = await moduleText(aiScoreSharesOf(readMeasurement(), allRules()));
  if (!process.argv.includes("--check")) writeFileSync(SHARES_MODULE, expected);
  else if (readFileSync(SHARES_MODULE, "utf8") !== expected) {
    console.error(`${SHARES_MODULE} is not what corpus/rules-measure.json gives (node scripts/ai-score-shares.ts)`);
    process.exitCode = 1;
  }
}
