// Builds packages/lang-en/lexicons/dictionary.txt, the English word list unknown-word checks spelling against.
// Usage: node scripts/en-dictionary.ts
// The words come from wink-lexicon, which the English adapter already installs through wink-pos-tagger: its lexicon of
// common inflected forms, the WordNet lemmas, and WordNet's irregular forms (abetted, abaci). No new package is added.
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "packages", "lang-en", "lexicons", "dictionary.txt");
const SOURCES = ["lexicon", "wn-words", "wn-noun-exceptions", "wn-verb-exceptions", "wn-adjective-exceptions"];
const WORD = /^[a-z]+$/u;

const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null && !Array.isArray(value);

const wordsOf = (source: string): string[] => {
  const loaded: unknown = require(`wink-lexicon/src/${source}.js`);
  if (!isRecord(loaded)) throw new Error(`wink-lexicon/src/${source}.js: not a word table`);
  return Object.keys(loaded).filter((word) => WORD.test(word));
};

const HEADER = [
  "# English words for chaff's unknown-word rule, one per line, generated by scripts/en-dictionary.ts. Do not edit by hand.",
  "# Derived from wink-lexicon (MIT, Copyright (c) 2017-23 GRAYPE Systems Private Limited), which includes data derived",
  "# from WordNet 3.0, Copyright 2006 by Princeton University (WordNet License: https://wordnet.princeton.edu/license-and-commercial-use).",
];

const words = [...new Set(SOURCES.flatMap(wordsOf))].toSorted((left, right) => left.localeCompare(right, "en"));
writeFileSync(OUT, [...HEADER, ...words, ""].join("\n"));
console.log(`${OUT}: ${String(words.length)} words`);
