// Writes the human baseline of the structure measures (packages/chaff/structure-baseline.yaml) from directories of
// Markdown articles written by people. The articles stay where they are: only the percentiles are written.
//
//   node scripts/structure-baseline.ts ja=<dir>[,<dir>…] en=<dir>[,<dir>…] > packages/chaff/structure-baseline.yaml
//   node scripts/structure-baseline.ts --values ja=<dir> > values.json   (every document's measures, for comparing sets)
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { adapter as ja } from "../packages/lang-ja/src/index.ts";
import { adapter as en } from "../packages/lang-en/src/index.ts";
import type { LanguageAdapter } from "../packages/chaff/src/plugin.ts";
import { buildDocument, teamRules } from "../packages/chaff/src/document.ts";
import { EMPTY } from "../packages/chaff/src/config/load.ts";
import { profileFor } from "../packages/chaff/src/profile/for-file.ts";
import { japaneseRatio } from "../packages/chaff/src/detect-language.ts";
import { FEATURE_IDS, structureFeaturesOf, type FeatureId } from "../packages/chaff/src/structure-shape/features.ts";
import { percentilesOf } from "../packages/chaff/src/structure-shape/baseline.ts";

const ADAPTERS: Readonly<Record<string, LanguageAdapter>> = { ja, en };
/** A Japanese article has at least this share of Japanese characters; an English one at most the second. */
const JAPANESE_ENOUGH = 0.2;
const ENGLISH_AT_MOST = 0.02;
const GENRE = "blog/tech";

type DocumentValues = { readonly file: string; readonly values: Partial<Record<FeatureId, number>> };

const isLanguage = (source: string, language: string): boolean =>
  language === "ja" ? japaneseRatio(source) >= JAPANESE_ENOUGH : japaneseRatio(source) <= ENGLISH_AT_MOST;

const valuesOf = (file: string, source: string, language: string, adapter: LanguageAdapter): DocumentValues => {
  const doc = buildDocument(file, source, adapter, teamRules(EMPTY), profileFor(EMPTY, file, source, language, GENRE));
  const values = Object.fromEntries(structureFeaturesOf(doc).flatMap((feature) => (feature.value === undefined ? [] : [[feature.id, feature.value]])));
  return { file, values };
};

const markdownIn = (dir: string): string[] =>
  readdirSync(dir)
    .filter((name) => name.endsWith(".md"))
    .toSorted((left, right) => left.localeCompare(right))
    .map((name) => join(dir, name));

const measureLanguage = (language: string, dirs: readonly string[]): DocumentValues[] => {
  const adapter = ADAPTERS[language];
  if (adapter === undefined) throw new Error(`no adapter for ${language}`);
  return dirs.flatMap(markdownIn).flatMap((file) => {
    const source = readFileSync(file, "utf8");
    return isLanguage(source, language) ? [valuesOf(file, source, language, adapter)] : [];
  });
};

/** One measure on one line: `heading-density: { measured: 2334, percentiles: { 5: 0, 10: 0.4, … } }`. */
const featureLine = (id: FeatureId, documents: readonly DocumentValues[]): string => {
  const values = documents.flatMap((document) => document.values[id] ?? []);
  const percentiles = Object.entries(percentilesOf(values)).map(([step, value]) => `${step}: ${String(value)}`);
  return `    ${id}: { measured: ${String(values.length)}, percentiles: { ${percentiles.join(", ")} } }`;
};

const languageBlock = (language: string, documents: readonly DocumentValues[]): string[] => [
  `${language}:`,
  `  articles: ${String(documents.length)}`,
  "  features:",
  ...FEATURE_IDS.map((id) => featureLine(id, documents)),
];

const args = process.argv.slice(2);
const sets = args
  .filter((arg) => arg.includes("="))
  .map((arg) => {
    const [language = "", dirs = ""] = arg.split("=");
    return { language, dirs: dirs.split(",").filter((dir) => dir !== "") };
  });
const measuredSets = sets.map((set) => ({ language: set.language, documents: measureLanguage(set.language, set.dirs) }));

if (args.includes("--values")) {
  console.log(JSON.stringify(Object.fromEntries(measuredSets.map((set) => [set.language, set.documents]))));
} else {
  const header = [
    "# The human baseline of the structure measures (chaff outline's structure block, the ai-structure rule).",
    "# Generated by scripts/structure-baseline.ts from articles written before generated text was common;",
    "# the articles themselves are not in the repository. Percentiles are nearest-rank, every five from 5 to 95.",
  ];
  console.log([...header, ...measuredSets.flatMap((set) => languageBlock(set.language, set.documents))].join("\n"));
}
